server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tijian?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hjm123456

  cache:
    redis:
      cache-null-values: true #当找不到数据时，缓存一个null值
      time-to-live: 120000   #设置键值对的过期时间
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    database: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.scau.edu.cn.doctor.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl